[package]
name = "leone-cuda"
description = "CUDA backend and handwritten kernels for Leone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
half.workspace = true
leone = { version = "0.3.0", path = "../leone" }
thiserror.workspace = true

[dev-dependencies]
leone-gguf = { version = "0.3.0", path = "../leone-gguf" }
rand = { version = "0.9.2", features = ["small_rng"] }
sha2.workspace = true
