[package]
name = "leone-cuda"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
half.workspace = true
leone = { path = "../leone" }
thiserror.workspace = true

[dev-dependencies]
leone-gguf = { path = "../leone-gguf" }
rand = { version = "0.9.2", features = ["small_rng"] }
sha2.workspace = true
