#!/usr/bin/env python3
"""Render the comparison report from generated receipts."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return json.loads((ROOT / path).read_text())


def quality_rows():
    lines = []
    for label, path in (("Qwen3 8B", "receipts/quality-concurrent-service.json"),
                        ("Llama 3.2 1B", "receipts/quality-llama-v03.json")):
        record = read(path)
        for subject in ("leone_q4", "llama_q4"):
            quality = record["executions"][subject]["quality"]
            lines.append(f"| {label} | {subject} | {quality['sample_count']} | "
                         f"{quality['kld']['mean']:.9f} | {quality['top1_agreement']:.9f} |")
    return lines


def render():
    study = read("receipts/concurrent-service-study.json")
    lines = ["# Concurrent service evidence", "",
             "This report is generated by `scripts/render-concurrent-evidence.py`.",
             "The complete record is [concurrent-service-study.json](../receipts/concurrent-service-study.json).", "",
             f"Model SHA-256: `{study['model']['sha256']}`.", "",
             "## Streaming comparison", "",
             f"The frozen workload uses {study['workload']['repetitions']} repetitions and "
             f"{study['workload']['request_count_per_repetition']} requests per repetition.",
             "Each run starts a fresh server. Variant order is balanced.",
             "TTFT ends at the first nonempty content event. Throughput includes prompt processing and stream completion.", "",
             "| Variant | Completed | Losses | TTFT p50 (ms) | TTFT p95 (ms) | Completion p95 (ms) | Aggregate throughput p50 (tok/s) |",
             "|---|---:|---:|---:|---:|---:|---:|"]
    for name in ("leone_batch1", "leone_batch4", "llama_server"):
        row = study["summary"][name]
        quantile = lambda metric, p: format(row[metric]["values"][p], ".3f")
        lines.append(f"| {name} | {row['completed_count']} | {row['loss_count']} | "
                     f"{quantile('ttft_ms', 'p50')} | {quantile('ttft_ms', 'p95')} | "
                     f"{quantile('completion_latency_ms', 'p95')} | {quantile('aggregate_completion_tok_s', 'p50')} |")
    lines += ["", "llama.cpp can decode all active slots. Leone limits each dispatch to one or four requests.",
              "The shared limits cover context, KV type, request schedule, sampling controls, and chat template.",
              "Prompt token counts match. The API does not expose prompt token identities.", "",
              "## Resident progress and physical memory", "",
              "| Variant | Runs with resident progress | Runs with disconnect recovery | Maximum tracked device bytes |",
              "|---|---:|---:|---:|"]
    for name in ("leone_batch1", "leone_batch4"):
        runs = [run for run in study["runs"] if run["variant"] == name]
        progress = sum(run["resident_trace"]["validation"]["resident_progress_proven"] for run in runs)
        recovery = sum(run["disconnect_recovery"]["passed"] for run in runs)
        peak = max(sample["memory"]["peak_live_bytes"] for run in runs for sample in run["resident_trace"]["body"]["memory_samples"])
        lines.append(f"| {name} | {progress} | {recovery} | {peak} |")
    lines += ["", "The trace requires decode between two positive prefill chunks of a different request.",
              "Device bytes include model weights, KV, activations, and retained workspaces.",
              "CUDA library and graph object byte sizes remain untracked. See [memory accounting](memory-accounting.md).", "",
              "## Common quality reference", "",
              "| Model | Subject | Scored positions | Mean KLD (nats) | Top-1 agreement |",
              "|---|---|---:|---:|---:|"]
    lines += quality_rows()
    lines += ["", "The BF16 or F16 llama.cpp oracle is independent of Leone. It shares code with the llama.cpp subject.",
              "Quality covers direct chunked evaluation. Exact CUDA differential tests cover the concurrent runtime path.", "",
              "## Limits", "",
              "- The comparison covers one RTX 4090 and one Qwen3 GGUF workload.",
              "- Content-event intervals use socket read-completion timestamps. They are not token intervals.",
              "- The harness records clocks and power during service. It does not lock clocks.",
              "- HTTP reads and writes can block the service thread. The workload uses prompt local clients.",
              "- Disconnect recovery observes a fresh session. The lifecycle tests separately check state release.",
              "- Results do not establish superiority over other engines, models, or hardware.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs/concurrent-service-evidence.md"
    output.write_text(render())
    print(output)
